version: "3"
services:
  www:
    build: .
    entrypoint: ./cmd/www/www
    ports:
      - "5000:5000"
  api:
    build: .
    entrypoint: ./cmd/api/api
    ports:
      - "8080:8080"
    links:
      - profile
      - search
  profile:
    build: .
    entrypoint: ./cmd/profile/profile
  search:
    build: .
    entrypoint: ./cmd/search/search
    links:
      - geo
      - rate
  geo:
    build: .
    entrypoint: ./cmd/geo/geo
  rate:
    build: .
    entrypoint: ./cmd/rate/rate
